---
title: "Addition and scalar multiplication: answers"
author: "Kin Wang Pang"
abstract-title: Summary
abstract: Answers to questions relating to the guide on addition and scalar multiplication.

---

*These are the answers to [Questions: Addition and scalar multiplication](qs-additionandscalarmultiplication.qmd).* **Please attempt the questions before reading these answers!**

## Q1 {-}

Solve the following questions.

1.1. For the $\hat{i}$ component, $4 + 8 = 12$.For the $\hat{j}$ component, $5 + 2 = 7$.For the $\hat{k}$ component, $7 + 4 = 11$. So the answer is $12\hat{i} + 7\hat{j} + 11\hat{k}$.

1.2. $2\hat{i} + 3\hat{j} + 9\hat{k}$.

1.3. $2\hat{i} - 11\hat{j} + 14\hat{k}$.

1.4. $i$th: $4- (3+11) = -10$, $j$th: $12- (-3-4) = 19$, $k$th: $-7-(-2+9) = -14$. So the answer is $-10\hat{i} + 19\hat{j} -14\hat{k}$.

## Q2 {-}

Solve the following questions.

2.1. $\pmatrix{4\alpha \\7\beta}$

2.2. $\pmatrix{7 \\ 3\beta - 2\alpha \\ -\gamma}$

2.3. $\vec{0}$ or $\pmatrix{0\\0\\0}$. This is different from the scalar $0$.

2.4. This question is erroneous. You cannot add $\vec{a}$ to a scalar $0$.

## Q3{-}

3.1. $3\vec{u} = (3\times5\hat{j}) + (3\times6\hat{k}) = 15\hat{j} + 18\hat{k}$.

3.2. $\pmatrix{0\\18\\42}$.

3.3. $\pmatrix{0\\-27\\10}$

3.4. $\pmatrix{-4\\-32\\-2}$

## Q4 {-}

4.1. $\vec{AB} = \vec{AO} + \vec{OB} = -\vec{OA} + \vec{OB}$, where $\vec{OA}$ and $\vec{OB}$ is the respective coordinates of $A$ and $B$ written in vector form. So $\vec{AB} = \pmatrix{-2-3\\5-4\\7-5} = \pmatrix{-5\\1\\2}$

4.2.$\vec{AB} = \pmatrix{4\\6\\0}$, $\vec{AC} = \pmatrix{-2\\-4\\-5}$. $\vec{AB} - \vec{AC} = \pmatrix{6\\10\\5}$. You can also calculate this by noticing $\vec{AB} - \vec{AC} = \vec{CA} + \vec{AB} = \vec{CB}$. Then $\vec{CB} = \pmatrix{6-0\\11-1\\7-2} = \pmatrix{6\\10\\5}$as required

4.3. $\vec{AB} = \lambda\vec{BC}$, where \lambda is a scalar. $\vec{AB} = \pmatrix{10\\-5}$, $\vec{BC} = \pmatrix{4k-12\\3k-4}$. This gives you the simultaneous equations $\begin{cases} 10 = \lambda(4k-12)\\-5 = \lambda(3k-4) \end{cases}$. Solving this gives $k = 2$.

4.4. $\vec{AB} = \vec{OB} - \vec{OA}$. $\pmatrix{1\\5\\9} - \pmatrix{a_1\\a_2\\a_3} = \pmatrix{6\\7\\-2}$. Solving this gives $A = (-5,-2,11)$.

4.5. $\lambda \vec{a} + \mu \vec{b} = 13\hat{i} -9\hat{j}$. This gives you the simultaneous equations $\begin{cases} 2\lambda + 3\mu = 13\\3\lambda -5\mu = -9 \end{cases}$. Solving this gives $\mu = 3$, $\lambda = 2$. Which gives the answer $2\vec{a} + 3\vec{b}$.

4.6. $2\pmatrix{2\\5\\\gamma} + 3\pmatrix{-1\\-3\\4} = \pmatrix{\alpha\\\beta\\0}$. Solving this gives $\alpha = 3$,$\beta = 1$ and $\gamma = -6$.

4.7. $\vec{a} = \lambda \vec{b}$. This gives the simultaneous equations $\begin{cases} k - 7 = -2\lambda\\5k+1 = 8\lambda \end{cases}$. Solving this gives $\k = 3$.

4.8. This gives the simultaneous equations $\begin{cases} \alpha + 5 = 2\alpha -2\\3-\beta = 3\beta + 8\\7-2 = \gamma + 12\\1+5 = 2\delta + 2\delta\end{cases}$. Solving this gives $\alpha = 3$,$\beta = -\frac{5}{4}$,$\gamma = -7$ and $\delta = \frac{3}{2}$.


