---
title: "Laws Of Indices: Answers"
author: "Akshat Srivastava"
abstract-title: Summary
abstract: "Answers to supplementary questions for the study guide on Laws Of Indices."
---

*These are the answers to [Laws Of Indices: Questions](qs-Lawsofindices.qmd)*

## Q1 {-}
Find the following:\
1.1. $(3)^4=81$\
1.2. $125^{\frac{2}{3}}=5^2=25$\
1.3. $32^{\frac{2}{5}}=2^2=4$\
1.4. $729^{\frac{-2}{3}}=9^{-2}=\frac{1}{81}$\
1.5. $4^3\cdot2^5=2^6\cdot2^5=2^{11}=2048$\
1.6. $9^2\div27^2=3^4\div3^6=3^{-2}=\frac{1}{9}$\
1.7. $(5^2)^2=5^4=625$\
1.8. $(35^0)^9=1$\
1.9. $(35^9)^0=1$\
1.10. $(729^9)^{\frac{1}{9}}=729^{\frac{9}{9}}=729$\
1.11. $7^{-3}=\frac{1}{343}$\
1.12. $64^{\frac{4}{3}}=4^4=256$\

## Q2 {-}
Simplify the following expressions:\
1.1. $(b^{7})^{4}=b^{28}$\
1.2. $y^{13}\cdot{y^{5}}=y^{18}$\
1.3. $x^{13}\div{x^{5}}=x^8$\
1.4. $(3y^{-2})^5=(3)^5\cdot(y^{-2})^5=243y^{-10}$\
1.5. $(7z^{-5})^3=(7)^3\cdot(z^{-5})^3=343z^{-15}$\
1.6. $(\frac{8x^5}{4x^{-5}})=2x^{(5+5)}=2x^{10}$\
1.7. $((2x)^{3}\cdot{x^{5}})=8x^3\cdot{x^5}=8x^8$\
1.8. $(\frac{2a^{-4}}{(3a)^{-2}})=(\frac{2}{3^{-2}})\cdot(a^{-4+2})=\frac{18}{a^2}$\
1.9. $((2y)^{3}\div{2y^{5}})=\frac{2^3\cdot{y^3}}{2y^5}=4y^{-2}$\
1.10. $(\frac{2}{a})^{4}\cdot(\frac{a}{12})^{3}=\frac{2^4\cdot{a^3}}{a^4\cdot{12^3}}=\frac{16}{1728a}=\frac{1}{108a}$\
1.11. $\frac{25t^{-4}}{60t^{5}}=\frac{5}{12t^9}$\

## Q3 {-}
Solve for x:\
2.1. $\sqrt[4]{x-4}=5\implies (x-4)^\frac{4}{4}=5^4 \implies x-4=625 \implies x=629$\
2.2. $x^4=2^8\implies x^4=4^4\implies x=4$\
2.3. $x^{0.5}=23\implies x=23^2 \implies x=529$\
2.4. $8^{2-x}=2^{4+3x}\implies 2^{3(2-x)}=2^{4+3x} \implies 6-3x=4+3x \implies 2=6x\implies x=\frac{1}{3}$\
2.5. $2^{3x}=10\implies3x\ln2=\ln10\implies x=\frac{\ln10}{3\ln2}$\
2.6. $5^{3-x}=625\implies5^{3-x}=5^4\implies3-x=4\implies x=-1$\
2.7. $7^{2-x}=4^{2x+3}\implies(2-x)\ln7=(2x+3)\ln4\implies2\ln7-x\ln7=2x\ln4+3\ln4\implies2\ln7-3\ln4=x(2\ln4+\ln7)\implies x=\frac{\ln(\frac{49}{64})}{\ln(112)}$\
2.8. $16=8^{3-7x}\implies2^4=2^{3(3-7x)}\implies4=9-21x\implies21x=5\implies x=\frac{5}{21}$\
2.9. $e^{3-8x}-9=0\implies e^{3-8x}=9\implies \ln(e^{3-8x})=\ln(9)\implies3-8x=2\ln3\implies x=\frac{3-2\ln3}{8}$\
2.10. $e^{4-3x}+8=12\implies e^{4-3x}=4\implies4-3x=\ln4\implies x=\frac{4-2\ln2}{3}$\
2.11. $\sqrt[3]{2^{4x}-4}=5\implies(2^{4x}-4)^\frac{3}{3}=5^3\implies2^{4x}-4=125\implies2^{4x}=129\implies4x\ln2=\ln129\implies x=\frac{\ln129}{4\ln2}$\
2.12. $\sqrt[3]{e^{2x}-13}=81^{\frac{1}{4}}\implies(e^{2x}-13)^\frac{3}{3}=3^3\implies e^{2x}-13=27\implies 2x=\ln40\implies x=\frac{\ln40}{2}$\
2.13. $\frac{5xa^{-7}b^{9}}{9a^2b^{-10}} = \frac{25b^{19}}{3a^9}\implies\frac{5xb^{(9+10)}}{9a^{(2+7)}}=\frac{25b^{19}}{3a^9}\implies\frac{5xb^{19}}{9a^9}=\frac{25b^{19}}{3a^9}\implies\frac{5x}{9}=\frac{25}{3}\implies15x=25\cdot9\implies x=15$\

---
