---
title: "Introduction To Vectors"
author: "Akshat Srivastava"
format: 
  html: 
    code-background: true
execute: 
  warning: false
---

---
 
```{r, setup, include = FALSE}
library("webexercises")
```

## Introduction {-}

In mathematics, physics, engineering and technology, you will come across two types of quantities, scalar quantities such as length, mass, time, distance, density, area, volume, temperature, work, etc. and vector quantities like position, displacement, velocity, acceleration, force, momentum, etc.

Vectors has various real-life applications across different fields, such as Engineering, Navigation and GPS, Computer Graphics and Gaming, Data Analysis and Machine learning, Cryptography and much more. In this guide, you will study some of the fundamental concepts about vectors, various operations on vectors, and their algebraic and geometric properties. 

::: {.callout-note}

## Definition of Scalars and Vectors

**Scalars**: Any physical quantity that has magnitude only and no direction are called scalar quantities. They are represented by a single real number along with appropriate units of measurement. They can be positive, negative or zero. 

**Vectors**: Any physical quantity that has both magnitude and direction is called a vector quantity. Besides this, a physical quantity, which is a vector, should also follow laws of vector addition. For example, electric current has both magnitude and direction, but it doesn’t follow laws of vector addition and hence is not a vector. (you will see this in the next chapter) 

:::

::: {.callout-note appearance="simple"}

## Example 1.1 
In classifying $15kg$, $45m/s^2$ and $70W$ as either a scalar or vector quantity, $15kg$ and $70W$ are scalar quantities because mass and power don't have direction, whereas, $45m/s^2$ is a vector quantity because accelaration needs direction.

:::

## Representation Of Vectors{-}
Consider a line AB in space and let a direction be assigned to it. The arrow marked on the line denotes the direction of the vector. Vectors are written with a little arrow over its head, for example, $\vec{AB}$. 

The direction in which the arrow points towards is called the head of a vector, which makes the other end, the tail of the vector. The length of the line indicates the magnitude of the vector and is denoted by $|\vec{AB}|$.

::: {.content-visible when-format="html"}

![Figure 1.1 shows the vector  $\vec{AB}$  whereas the Figure 1.2 shows the vector  $\vec{BA}$.]

:::

::: {.callout-note appearance="simple"}

## Example 1.2

A car A travels from point P to point Q with a velocity of $80 km/hr$. Simultaneously, a car B starts travelling from point Q to point P with the same velocity. In this case,  $\vec{PQ}=80km/hr$ for car A and $\vec{QP}=80km/hr$ for car B.

:::

::: {.callout-note appearance="simple"}
 
## Example 1.3

Continuing the Example 1.2, consider the car B to be travelling in the same direction as car A but with half the velocity. Visually, the velocity vector would also become half for the second car.

:::

## Free and Localized Vectors{-}

If the initial point of a vector can be chosen then the vector is said to be a free vector. A free vector can be displaced parallel to itself as long as the magnitude and the direction stay the same. If the initial point is restricted to a specific point then that vector is called a localized vector.

::: {.callout-note appearance="simple"}
 
## Example 1.4

Force, momentum, impulse are some examples of free vectors because they are scalar and independent of position, whereas, displacement and velocity vectors are localized vectors because they are vectors and dependent on position.

:::

## Different types of vectors{-}

- **Zero or Null Vector**: A vector $\vec{a}$ is said to be a zero or a null vector if its magnitude is zero. For example, a stationary body has the velocity vector as zero.

- **Like and Unlike Vectors**: Vectors having the same direction are known as like vectors whereas vectors with opposite directions are called unlike vectors. These are also called parallel and anti-parallel vectors respectively too.

- **Collinear Vectors**: A vector is said to be collinear if it is coincident with the given vector, i.e., they have the same direction but need not have the same magnitude.

- **Coplanar Vectors**: Vectors are coplanar if they are parallel to the same plane or lying on the same plane.

- **Equal Vectors**: Vectors are said to be equal if they have the same magnitude as well as the direction. 

- **Negative Vector**: A vector whose magnitude is the same as that of the given vector $\vec{a}$ but is in the opposite direction is called the negative of a vector and is denoted by -$\vec{a}$. These are also collinear vectors.

::: {.callout-note appearance="simple"}

## Example 1.5

When a ball is dropped from a height, gravity acts in the same direction as the motion of the ball, hence, the gravitational force $\vec{g}=10m/s^2$. A negative gravitational force would mean that gravity is working in the opposite direction of the motion, which is the case of a vertically projected body, here, $-\vec{g}$ is applied.

:::


## Vectors In Three-Dimensional Space{-}
A vector $\vec{a}$ can be expressed in two-dimensional and three-dimensional space through various coordinate systems. You will see the standard cartesian coordinate system in this guide.

##### $\mathbf{Unit Vectors}$

Unit vectors are vectors whose magnitude is exactly 1 unit. These are represented by the symbol $‘^’$, which is called a cap or a hat. Consider the vector $\vec{a}$. Then the unit vector of $\vec{a}$ would be the actual vector divided by its magnitude: 

$\hat{a}=\frac{\vec{a}}{|\vec{a}|}$

In a three-dimensional space, $\hat{i}$, $\hat{j}$, $\hat{k}$ are the unit vectors along the x-axis, y-axis and z-axis respectively. These are also written like $\mathbf{i},\mathbf{j},\mathbf{k}$ and any vector in the cartesian coordinate system can be generally represented in terms of this.

Any vector $\vec{a}$ can be expressed in the format

$\vec{a}=x\mathbf{i}+y\mathbf{j}+z\mathbf{k}$, where $x,y,z \in \mathbb{R}$ 

where x is the distance along the x-axis, y is the distance along they-axis and z is the direction along the z-axis.

::: {.callout-note appearance="simple"}

## Example 1.6

You are given a vector $\vec{a}=2\mathbf{i}+5\mathbf{j}+4\mathbf{k}$, this means that the vector $\vec{a}$ is a free vector with 2 units along the x-axis, 5 units along the y-axis and 4 units along the z-axis. 

:::

::: {.callout-note appearance="simple"}

## Example 1.7

You are given a vector $\vec{b}=-7\mathbf{k}+3\mathbf{i}$, this means that the vector $\vec{b}$ is a free vector with 3 units along the x-axis, 0 units along the y-axis and 7 units along the negative z-axis. This means that the vector lies in the x-z plane, making it a two-dimensional vector.

:::

::: {.callout-note appearance="simple"}

## Example 1.8

You are given a vector $\vec{c}=25\mathbf{i}$, this means that the vector $\vec{c}$ has direction only along the x-axis and a magnitude of 25. This a one-dimensional vector.

:::

##### $\mathbf{Column Vectors}$

This is another way of representing vectors. A column vector is a vector whose components are listed vertically in a single column.
So, a vector $\vec{a}$ can be written as:

$\vec{a}=x\mathbf{i}+y\mathbf{j}+z\mathbf{k}=\begin{pmatrix}x\\y\\z\end{pmatrix}$, where $x,y,z \in \mathbb{R}$  

::: {.callout-note appearance="simple"}

## Example 1.9

You are given the vector $\vec{l}=3\mathbf{i}-4\mathbf{j}+5\mathbf{k}$, to represent this vector in column notation you make a $3 \times 1$ matrix with entries 3,-4 and 5 respectively. So, $\vec{l}=3\mathbf{i}-4\mathbf{j}+5\mathbf{k}=\begin{pmatrix}3\\-4\\5\end{pmatrix}$

:::

::: {.callout-note appearance="simple"}

## Example 1.10

To find if the vectors in Example 1.9 and $\vec{d}=\begin{pmatrix}6\\-8\\10\end{pmatrix}$ are parallel or not, you check if the coefficients are the same or a multiple of it. Since $\frac{3}{6}=\frac{-4}{-8}=\frac{5}{10}=\frac{1}{2}$ hence, these two vectors $\vec{l}$ and $\vec{d}$ are parallel to each other.

:::

::: {.callout-note appearance="simple"}

## Example 1.11

To express the vector $\vec{B}=\begin{pmatrix}7\\1\\4\end{pmatrix}$ in terms of $\mathbf{i},\mathbf{j},\mathbf{k}$, you can write $\vec{B}=\begin{pmatrix}7\\1\\4\end{pmatrix}=7\mathbf{i}+\mathbf{j}+4\mathbf{k}$

:::

##### $\mathbf{Position Vectors}$

Vectors that indicate the position of a body are known as position vectors. Consider a point P in space, having coordinates $(x,y,z)$ with respect  to the origin $O(0,0,0)$. Then, the vector $\vec{OP}$ is the position vector for the point P. This is also represented through the $\vec{r}$ vector.

$\vec{r}=x\mathbf{i}+y\mathbf{j}+z\mathbf{k}$, where $x,y,z \in \mathbb{R}$ 

Then the magnitude of the position vector $\vec{r}$ is given by $|\vec{r}|=\sqrt{x^2+y^2+z^2}$.

Any vector $\vec{a}=x\mathbf{i}+y\mathbf{j}+z\mathbf{k}$ can have its unit vector expressed as 

$\hat{a}=\frac{\vec{a}}{|\vec{a}|}=\frac{x\mathbf{i}+y\mathbf{j}+z\mathbf{k}}{|\vec{a}|}=\frac{x\mathbf{i}+y\mathbf{j}+z\mathbf{k}}{\sqrt{x^2+y^2+z^2}}$

So, $\hat{a}=\frac{x\mathbf{i}+y\mathbf{j}+z\mathbf{k}}{\sqrt{x^2+y^2+z^2}}$

::: {.callout-note appearance="simple"}

## Example 1.12

The vector given is $\vec{p}=\mathbf{i}+4\mathbf{j}-9\mathbf{k}$, to find the unit vector for this, you find the magnitude of this vector, $|\vec{p}|=\sqrt{1^2+4^2+(-9)^2}$. Then the unit vector is $\hat{p}=\frac{\mathbf{i}+4\mathbf{j}-9\mathbf{k}}{\sqrt{1^2+4^2+(-9)^2}}=\frac{\mathbf{i}+4\mathbf{j}-9\mathbf{k}}{\sqrt{98}}=\frac{1}{7\sqrt{2}}\mathbf{i}+\frac{4}{7\sqrt{2}}\mathbf{j}-\frac{9}{7\sqrt{2}}\mathbf{k}$

:::

::: {.callout-note appearance="simple"}

## Example 1.13

The vector given is $\vec{q}=-4\mathbf{i}+2\mathbf{j}+11\mathbf{k}$, to find the unit vector for this, you find the magnitude of this vector, $|\vec{q}|=\sqrt{(-4)^2+2^2+11^2}=\sqrt{141}$. Then the unit vector is $\hat{q}=\frac{-4\mathbf{i}+2\mathbf{j}+11\mathbf{k}}{\sqrt{141}}=-\frac{4}{\sqrt{141}}\mathbf{i}+\frac{2}{\sqrt{141}}\mathbf{j}+\frac{11}{\sqrt{141}}\mathbf{k}$

:::




