---
title: "Introduction to vectors: answers"
author: "Zheng Chen"
abstract-title: Summary
abstract: Answers to questions relating to the guide on introduction to vectors
---

*These are the answers to [Questions: Introduction to vectors](qs-introductiontovectors.qmd).* **Please attempt the questions before reading these answers!**

## Q1 {-}
 
Identify the following as either scalar or vector quantities.

1.1. length: scalar, area: scalar, displacement: vector

1.2. velocity: vector, pressure: scalar, power: scalar

1.3. work: scalar, force: vector, acceleration: vector 

1.4. momentum: vector, density: scalar, speed: scalar

1.5. temperature: scalar, volume: scalar, energy: scalar


## Q2 {-}

Find the magnitude of the following vectors.

2.1. $|\vec{A}| = \sqrt{(-1)^2 + 3^2} = \sqrt{1+9} = \sqrt{10}$

2.2. $|\vec{B}| = \sqrt{2^2+4^2+6^2} = \sqrt{4+16+36} = \sqrt{56} = 2\sqrt{14}$

2.3. $|\vec{C}| = \sqrt{1^2+(-1)^2+4^2} = \sqrt{1+1+16} = \sqrt{18} = 3\sqrt{2}$

2.4. $|\vec{D}| = \sqrt{5^2+(-2)^2+1^2} = \sqrt{25+4+1} = \sqrt{30}$

2.5. $|\vec{E}| = \sqrt{2^2+(-1)^2+4^2} = \sqrt{4+1+16} = \sqrt{21}$

2.6. $|\vec{F}| = \sqrt{(-3)^2+6^2+2^2} = \sqrt{9+36+4} = \sqrt{49} = 7$

2.7. $|\vec{G}| = \sqrt{5^2+1^2+(\sqrt{2})^2} = \sqrt{25+1+2} = \sqrt{28} = 2\sqrt{7}$

2.8. $|\vec{H}| = \sqrt{6^2+2^2+2^2} = \sqrt{36+4+4} = \sqrt{44} = 2\sqrt{11}$

2.9. $|\vec{I}| = \sqrt{(-3)^2+3^2+(-3)^2} = \sqrt{9+9+9} = \sqrt{27} = 3\sqrt{3}$

2.10. $|\vec{J}| = \sqrt{2^2+4^2+4^2} = \sqrt{4+16+16} = \sqrt{36} = 6$

2.11. $|\vec{K}| = \sqrt{8^2+(-2)^2+16^2} = \sqrt{64+4+256} = \sqrt{324} = 18$

2.12. $|\vec{L}| = \sqrt{5^2+(-2)^2+14^2} = \sqrt{25+4+196} = \sqrt{225} = 15$

2.13. $|\vec{M}| = \sqrt{7^2+2^2+(-1)^2} = \sqrt{49+4+1} = \sqrt{54} = 3\sqrt{6}$

2.14. $|\vec{N}| = \sqrt{12^2+9^2+8^2} = \sqrt{144+81+64} = \sqrt{289} = 17$



## Q3 {.unnumbered}

Find the unit vectors for the vectors in Q2

3.1. $\hat{A}=\frac{-1\mathbf{i}+3\mathbf{j}}{\sqrt{10}}=\frac{-1}{\sqrt{10}}\mathbf{i}+\frac{3}{\sqrt{10}}\mathbf{j}$

3.2. $\hat{B}=\frac{2\mathbf{i}+4\mathbf{j}+6\mathbf{k}}{2\sqrt{14}}=\frac{1}{\sqrt{14}}\mathbf{i}+\frac{2}{\sqrt{14}}\mathbf{j}+\frac{3}{\sqrt{14}}\mathbf{k}$

3.3. $\hat{C}=\frac{\mathbf{i}-1\mathbf{j}+4\mathbf{k}}{3\sqrt{2}}=\frac{1}{3\sqrt{2}}\mathbf{i}-\frac{1}{3\sqrt{2}}\mathbf{j}+\frac{4}{3\sqrt{2}}\mathbf{k}$

3.4. $\hat{D}=\frac{5\mathbf{i}-2\mathbf{j}+\mathbf{k}}{\sqrt{30}}=\frac{5}{\sqrt{30}}\mathbf{i}-\frac{2}{\sqrt{30}}\mathbf{j}+\frac{1}{\sqrt{30}}\mathbf{k}$

3.5. $\hat{E}=\frac{2\mathbf{i}-\mathbf{j}+4\mathbf{k}}{\sqrt{21}}=\frac{2}{\sqrt{21}}\mathbf{i}-\frac{1}{\sqrt{21}}\mathbf{j}+\frac{4}{\sqrt{21}}\mathbf{k}$

3.6. $\hat{F}=\frac{-3\mathbf{i}+6\mathbf{j}+2\mathbf{k}}{7}=-\frac{3}{7}\mathbf{i}-\frac{6}{7}\mathbf{j}+\frac{2}{7}\mathbf{k}$

3.7. $\hat{G}=\frac{5\mathbf{i}+\mathbf{j}+\sqrt{2}\mathbf{k}}{2\sqrt{7}}=\frac{5}{2\sqrt{7}}\mathbf{i}+\frac{1}{2\sqrt{7}}\mathbf{j}+\frac{\sqrt{2}}{2\sqrt{7}}\mathbf{k}$

3.8. $\hat{H}=\frac{6\mathbf{i}+2\mathbf{j}+2\mathbf{k}}{2\sqrt{11}}=\frac{3}{\sqrt{11}}\mathbf{i}+\frac{1}{1\sqrt{11}}\mathbf{j}+\frac{1}{\sqrt{11}}\mathbf{k}$

3.9. $\hat{I}=\frac{-3\mathbf{i}+3\mathbf{j}-3\mathbf{k}}{3\sqrt{3}}=-\frac{1}{\sqrt{3}}\mathbf{i}+\frac{1}{\sqrt{3}}\mathbf{j}-\frac{1}{\sqrt{3}}\mathbf{k}$

3.10. $\hat{J}=\frac{2\mathbf{i}+4\mathbf{j}+4\mathbf{k}}{6}=\frac{1}{3}\mathbf{i}+\frac{2}{3}\mathbf{j}+\frac{2}{3}\mathbf{k}$

3.11. $\hat{K}=\frac{8\mathbf{i}-2\mathbf{j}+16\mathbf{k}}{18}=\frac{4}{9}\mathbf{i}-\frac{1}{9}\mathbf{j}+\frac{8}{9}\mathbf{k}$

3.12. $\hat{L}=\frac{5\mathbf{i}-2\mathbf{j}+14\mathbf{k}}{15}=\frac{1}{3}\mathbf{i}-\frac{2}{15}\mathbf{j}+\frac{14}{15}\mathbf{k}$

3.13. $\hat{M}=\frac{7\mathbf{i}+2\mathbf{j}-1\mathbf{k}}{3\sqrt{6}}=\frac{7}{3\sqrt{6}}\mathbf{i}+\frac{2}{3\sqrt{6}}\mathbf{j}-\frac{1}{3\sqrt{6}}\mathbf{k}$

3.14. $\hat{L}=\frac{12\mathbf{i}+9\mathbf{j}+8\mathbf{k}}{17}=\frac{12}{17}\mathbf{i}+\frac{9}{17}\mathbf{j}+\frac{8}{17}\mathbf{k}$