---
title: "Introduction to the Laws of indices"
author: "Zheng Chen"
abstract-title: Summary
abstract: The laws of indices enable expressions involving powers to be manipulated more efficiently than writing them out in full.
---

```{r, setup, include = FALSE}
library("webexercises")
```

*Before reading this guide, it is recommended that you read (Guide: Introduction to Logarithms) and (Guide: Dealing with powers and nth roots).*

## What are indices? {.unnumbered}

Indices are used to display how many times a number has been multiplied by itself. They can also be used to represent roots and fractions, such as the square root. The laws of indices make it possible to alter expressions involving powers more quickly than if they were written out whole.

This guide will introduce six properties of indices: multiplication, division, brackets,  powers of zero, negative indices, fractional indices and Euler's number: $e$.

::: callout-note

## Definition of an index

A number or a variable may have an **index**. The **index** of a variable (or a constant) is a value that is raised to the power of the variable. Indices are also known as powers or exponents. It shows the number of times a given number has to be multiplied. It is represented in the form:

$$ a^m = a· a· a · \ ... \ · a (m \ times)$$ 

Here, $a$ is the base and $m$ is the index.
:::

::: {.callout-note appearance="simple"}

## Example 1

$$2^5 = 2·2·2·2·2 = 32$$

In this example, $2$ is the base and $3$ is the index.
:::

## Laws of indices

::: callout-note

## Law 1: Multiplication

If the two terms have the same base (in this case $a$) and are multiplied together, then their indices are **added** (in this case $m+n$):

$$a^m·a^n = a^{m+n}$$ For example: $$3^2·3^3 = 9·27 = 243 = 3^5 = 3^{2+3}$$
:::

::: {.callout-note appearance="simple"}

## Example 2

Simplify the following expression: $x^2y^3· x^3y^{-1}$

You can treat $x$ and $y$ as two separate terms and you are now simplifying $x^2·x^3$ and $y^3·y^{-1}$. Using Law 1, you can add the indices to get: $x^{2+3}$ and $y^{3+(-1)}$. Remembering to multiply the $x$ and $y$ terms, you then get: $$x^2y^3· x^3y^{-1} = x^{2+3}y^{3-1} = x^5y^2$$
:::

::: {#law-2-link .callout-note}

## Law 2: Division

If the two terms have the same base (in this case $a$) and are to be divided, then their indices are **subtracted** (in this case $m-n$):

$$\frac{a^m}{a^n} = a^{m-n}$$ For example: $$\frac{2^5}{2^3} = 4 = 2^2 = 2^{5-3}$$
:::

::: {.callout-note appearance="simple"}

## Example 3

Simplify the following expression: $\frac{x^2y^3}{x^5y}$

You can treat $\frac{x^2y^3}{x^5y}$ as the product of two fractions: $\frac{x^2}{x^5}$ and $\frac{y^3}{y}$.\
Using Law 2, you can simplify the fractions to get:\ $\frac{x^2}{x^5} = x^{2-5} = x^{-3}$ and $\frac{y^3}{y} = y^{3-1} = y^2$, remembering to multiply the fractions, you get: $$\frac{x^2y^3}{x^5y} = x^{2-5}y^{3-1} = x^{-3}y^2$$
:::

::: {#law-3-link .callout-note}

## Law 3: Brackets

To raise a value or variable (in this case $a$) presented in index form to another index, **multiply** the indices together ($m$ and $n$):

$$(a^m)^n = a^{m·n}$$ For example: $$(3^2)^3 = 729 = 3^6 = 3^{2·3}$$
:::

::: {.callout-note appearance="simple"}

## Example 4

Simplify the following expression: $(x^2y^3)^4$

Using Law 3, you get:\
$(x^2y^3)^4 = (x^2)^4·(y^3)^4 = x^{2·4}y^{3·4} = x^8y^{12}$
:::

::: {#law-4-link .callout-note}

## Law 4: Power of $0$

Anything to the power of zero is equal to one:

$$a^0 = 1$$ 
:::

::: {.callout-note appearance="simple"}

## Example 5

Simplify the following expression: $(x^2 + y^5)^0$

Using Law 4, you get:\
$(x^2 + y^5)^0 = 1$
:::

::: {.callout-note appearance="simple"}

## Example 6

$$0^0 = 1$$

see [Zero to the power of zero](https://en.wikipedia.org/wiki/Zero_to_the_power_of_zero) for more explanation.
:::

::: callout-tip

## Proof of Law 4

[Law 2](#law-2-link) helps to explain Law 4:

Since anything divided by itself is equal to one, so $$\frac{a^m}{a^m} = 1$$

Also,

$$\frac{a^m}{a^m} = a^{m-m} = a^0 = 1$$ Therefore, $$a^0 = 1$$
:::

::: {.callout-note icon="false"}

## Note

Anything to the power of one is equal to itself $$a^1 = a$$ 

$1$ to the power of anything is $1$
:::

::: callout-note

## Law 5: Negative indices

If the index is a negative value, then it can be shown as the reciprocal of the positive index raised to the same variable:

$$a^{-m} = \frac{1}{a^m}$$ 

For example: $$2^{-2} = (2^2)^{-1} = 4^{-1} = \frac{1}{4} = \frac{1}{2^2}$$ 

In this case, [Law 3](#law-3-link) is used to simplify the base $2^2$ to $4$, then Law 5 is applied.

Alternatively,

$$2^{-2} = 2^{0-2} = \frac{2^0}{2^2} = \frac{1}{2^2}$$ 

In this case, [Law 4](#law-4-link) is used to re-express the index and [Law 2](#law-2-link) is used.
:::

::: {.callout-note appearance="simple"}

## Example 7

Simplify the following expression: $(3x+4y)^{-1}$

Using Law 5, you get:\
$(3x+4y)^{-1} = \frac{1}{3x+4y}$
:::

::: callout-note

## Law 6: Fractional indices

An index in the form of a fraction can be represented as the radical form:

$$a^{\frac{m}{n}} = (\sqrt[n]{a})^m$$ For example: $$2^{\frac{3}{5}} = \sqrt[5]{2^3} = \sqrt[5]{8}$$
:::

::: {.callout-note appearance="simple"}

## Example 8

Simplify $27^{\frac{-2}{3}}$

Using Law 7, you get $27^{\frac{-2}{3}} = (\sqrt[3]{27})^{-2} = 3^{-2} = \frac{1}{3^2} = \frac{1}{9}$
:::

# Solving equations using indices

You can use laws of indices to solve equations, here are some examples:

::: {.callout-note appearance="simple"}

## Example 9

Solve $x^{\frac{1}{2}}=8$

Start by squaring both sides of the equation to get $(x^{\frac{1}{2}})^2 = 8^2$, then you get the answer $x = 64$. To check if the answer is correct, you can substitute $64$ back into the equation: $64^{\frac{1}{2}} = \sqrt[2]{64}=8$.
:::

::: {.callout-note appearance="simple"}

## Example 10

Solve $x^{-2}=9$

$x^{-2} = 9$ can be re-expressed as $\frac{1}{x^2} = 9$.
Multiplying both sides by $x^2$ gives you $1=9x^2$.
Then dividing both sides by $9$ gives you $\frac{1}{9}=x^2$.
Now you can square root both sides to obtain: $\sqrt[2]{\frac{1}{9}}=x$.
Remember you can have positive and negative roots. Therefore, you get $x= \frac{1}{3}$ or $x= -\frac{1}{3}$.
:::

::: {.callout-note appearance="simple"}

## Example 11

Solve $3^{4x}=27^{5-x}$

As $27=3^3$, the equation can be rewritten as: $3^{4x}=(3^3)^{5-x}$. Then using the laws of indices, $3^{4x}=3^{15-3x}$. Since both sides are equal, $4x=15-3x$.
Then, $x=\frac{15}{7}$.
:::

## Introduction to $e$

::: callout-note

## Euler's number

**Euler's number**, denoted $e$, is a constant approximately equal to $2.71828$. It is the base of natural logarithms. It can be also calculated as the sum of the infinite series:

$$e = \sum_{n=0}^{\infty} \frac{1}{n!} = 1+\frac{1}{1!}+\frac{1}{2!}+\frac{1}{3!}+ \cdots$$
:::

::: {.callout-note appearance="simple"}

## Example 12

Solve $e^{3x}=12$

Taking the logarithm of both sides gives you $\log_e(e^{3x})=\log_e(12)$.\
$\log_e(x)$ is the natural logarithm often denoted $\ln(x)$, so you can write the equation as $\ln(e^{3x})=\ln(12)$. \
Using the power rule of logarithms, you can express the equation as $3x \cdot \ln(e) = \ln(12)$, then by the identity rule, you can get $3x \cdot (1)=\ln(12)$. Rearranging the equation gives you $x=\frac{\ln(12)}{3}$.

:::

## Quick check problems {.unnumbered}

<!-- add facility for webexercises to work on html -->

::: {.content-visible when-format="html"}

<!-- add facility to check answers at end rather than one at a time -->

::: {.webex-check .webex-box}

1. Solve $\sqrt[3]{9x-1}=4$

Answer: It is `r fitb("$\frac{65}{9}$")`

2. Solve $x^{\frac{2}{3}}=4\frac{17}{27}$

Answer: It is `r fitb("$\frac{25}{9}$")`

3. Determine whether the following calculations are correct:

(a) $\frac{17x^{17}y^{14}}{15x^{18}y^{18}} = \frac{17}{15xy}$ `r torf(FALSE)`

(b) $(5x^2·2x^5·3x^4)^2 = 900x^{22}$ `r torf(TRUE)`

(c) $\frac{12x^{14}y^{-4}}{12x^7y^{11}} = \frac{x^6}{y^7}$ `r torf(FALSE)`
:::

:::

::: {.content-hidden when-format="html"}

1. Solve $\sqrt[3]{9x-1}=4$

2. Solve $x^{\frac{2}{3}}=4\frac{17}{27}$

3. Determine whether the following calculations are correct:

(a) $\frac{17x^{17}y^{14}}{15x^{18}y^{18}} = \frac{17}{15xy}$ 

(b) $(5x^2·2x^5·3x^4)^2 = 900x^{22}$ 

(c) $\frac{12x^{14}y^{-4}}{12x^7y^{11}} = \frac{x^6}{y^7}$

:::

[For more questions on the subject, please go to Questions: Laws of indices](qs-lawsofindices.qmd)
