---
title: "Introduction to Logarithms"
author: "Ritwik Anand"
abstract-title: Summary
abstract: Using logarithms to condense large numbers is a fundamental skill when working in Mathematics. Understanding the laws of logarithms, working with the natural logarithm and learning how to change the base of a logarithm are key in mastering their functionality.
---

*Before reading this guide, it is recommended that you read the guides on 'Laws of indices', as well as 'Dealing with powers and nth roots'.*

## What are Logarithms?

In the same way that subtraction 'undoes' addition, and division 'undoes' multiplication, you can think of the logarithm as the function that 'undoes' exponentiation. Logarithms are useful because they essentially let you work backwards through a calculation by undoing exponential effects. Furthermore, logarithms allow us to express large numbers in a convenient way, as well as model various phenomena as they occur in a logarithmic fashion. An example would be a hot object cooling down; this decays logarithmically.

In this guide, you will learn the definition of a logarithm, the laws concerning logarithms, what the natural logarithm is and finally, how to change the base of a logarithm.

::: {#definition-1-link .callout-note}
## Definition of a Logarithm

In its simplest form, a logarithm answers "How many of one number multiply together to make another number." This is what motivates the following definition:

$$ a^x = b$$ or

$$\log_a(b) = x $$ where $x$ is the *exponent*, $a$ is the *base* and $b$ is the *argument*. You would read the equation above as "logarithm of $b$ to the base $a$ is equal to $x$."
:::

::: callout-important
Note that the logarithm function can only evaluate **real, positive numbers**. Therefore, you can't compute the logarithm of any number that is lesser than or equal to $0$.
:::

::: {#example-1-link .callout-note appearance="simple"}
## Example 1

Suppose you are given the equation $\log_{10}(1000) = x$, and you need to find $x$. You can rewrite the equation as $2^x = 8$, and from here, you can see that $x = 3$.
:::

::: {.callout-note appearance="simple"}
## Example 2

Now consider the equation $\log_x(8) = 3$. Rewriting this, you can see that this is equal to $x^3 = 8$. Therefore $x = 2$.
:::

::: callout-important
# Tom said something about how mathematicians use 10, physicists and compsci use different values or something. Look into it.

Generally, if the base is not specified, it is assumed that the base is 10. So for example, $\log(a) = b$ means that the logarithm of $a$ to the base $10$ is equal to $b$.
:::

::: {.callout-note appearance="simple"}
## Example 3

Consider the equation from [Example 1](#example-1-link). This can be rewritten as $\log(1000) = x$, and the solution for $x$ is once again $x = 3$
:::

## Laws of Logarithms

There are several rules of logarithms that allows us to expand, condense and solve logarithmic equations, and they are as follows:

::: {#product-rule-link .callout-note}
## Law 1: Product Rule

$$\log(M \cdot N) = \log(M) + \log(N)$$ The logarithm of a product is the sum of the logarithms of the factors.

For example:

$$\log(100) = \log(10 \cdot 10) = \log(10) + \log(10)$$
:::

::: callout-note
## Law 2: Quotient Rule

$$\log\left(\frac{M}{N}\right) = \log(M) - \log(N) $$ The logarithm of a ratio of two numbers is equal to the logarithm of the **numerator** minus the logarithm of the **denominator**

For example:

$$\log\left(\frac{5}{4}\right) = \log(5) - \log(4)$$
:::

::: {#law-3-link .callout-note}
## Law 3: Power Rule

$$\log(M^k) = k \cdot \log(M)$$ The logarithm of an exponential number is the exponent multiplied with the logarithm of the base.

For example:

$$\log(4) = \log(2^2) = 2 \cdot \log(2)$$
:::

::: callout-note
## Law 4: Zero Rule

$$\log_b(1) = 0$$ The logarithm of 1 to any base is **always** equal to 0.
:::

::: callout-note
## Law 5: Identity Rule

$$\log_b(b) = 1$$

The logarithm of the argument, where the argument is the base of the logarithm, is **always** equal to 1.
:::

# The Natural Logarithm

The natural logarithm is a mathematical function used to study problems specifically involving exponential growth and decay. Unlike the logarithms we encountered above, this logarithm always has a special base called **Euler's number**, denoted *e*.

::: {#definition-2-link .callout-note}
## The Natural Logarithm

The **natural logarithm**, often denoted $\ln(x)$, is $\log_e(x)$.
:::

The Natural Logarithm shares the same domain as the logarithms above, namely that it only evaluates **positive, real** numbers. All of the laws from above apply as well.

::: {.callout-note appearance="simple"}

## Example 4

Suppose you're given the equation $\ln(x) = 4$, and you've been asked to find $x$.

Using the definiton of a [natural logarithm](#definition-2-link), you can show that $\log_e(x) = 4$. Then, using the definition of a [logarithm](#definition-1-link), you can conclude that $x = e^4$.


:::


The Natural Logarithm is quite useful as it's the **inverse** of the exponential function with base *e*. 

::: {#example-5-link .callout-note appearance="simple"}

## Example 5

Let's say that you've been given the equation $e^x = 5$, and you need to solve for $x$. Taking the natural log on both sides of the equation gives us
$$\ln(e^x) = \ln(5)$$ Now, using [Law 3](#law-3-link), you can write the equation as  $$x\ln(e) = \ln(5)$$
From here, dividing both sides by $\ln(e)$ results in $$x = \frac{\ln(5)}{\ln(e)}$$

However, you know from the [definition](#definition-1-link) of the logarithm that $\ln(e) = \log_e(e)$. Finally, as $e^1 = 1$, you can show that $\ln(e) = \log_e(e) = 1$.

Therefore, $x = \ln(5)$.

:::

[Example 5](#example-5-link) shows you that $\ln(e) = 1$. This can be generalised for logarithms of any base.


::: callout-note
## Law 6: Inverse of a logarithm

$$\log_b(b^k) = k$$ The logarithm of an exponential where the base is equal to the base of the logarithm is equal to the exponent.
:::

::: callout-note
## Law 7: Inverse of an exponent

$$b^{log_b(k)} = k$$ Raising a logarithm of a number to its own base is equal to the number itself.
:::

