---
title: "The Scalar Product: Questions"
author: "Ritwik Anand"
abstract-title: Summary
abstract: A selection of questions for the study guide on the Scalar Product
---

*Before attempting these questions, it is highly recommended that you read [Guide: The Scalar Product](Scalar_Product2.qmd), as well as the [Guide: Introduction to Quadratic Equations](introtoquadratics.qmd). *

## Questions {-}

### 1 {-}

Find the scalar product of $\vec{u}$ and $\vec{v}$.

1.1. $\vec{u} = \begin{pmatrix}6\\3\\4\end{pmatrix}$ and $\vec{v} = \begin{pmatrix}1\\4\\2\end{pmatrix}$

1.2. $\vec{u} = \begin{pmatrix}10\\-7\\4\end{pmatrix}$ and $\vec{v} = \begin{pmatrix}3\\-5\\13\end{pmatrix}$

1.3. $\vec{u} = \begin{pmatrix}-4.4\\-1.2\\0.3\end{pmatrix}$ and $\vec{v} = \begin{pmatrix}6.1\\-2.5\\9.3\end{pmatrix}$
 
1.4. $\vec{u} = \begin{pmatrix}54\\38\\0\end{pmatrix}$ and $\vec{v} = \begin{pmatrix}32\\-55\\13\end{pmatrix}$

1.5. $\vec{u} = 2\mathbf{i} + 7\mathbf{j} + \mathbf{k}$ and $\vec{v} = 6\mathbf{i} + 4\mathbf{j} + 8\mathbf{k}$

1.6. $\vec{u} = -3\mathbf{i} + 10\mathbf{j} - 8\mathbf{k}$ and $\vec{v} = \mathbf{i} - 12\mathbf{j} + 9\mathbf{k}$

1.7. $\vec{u} = 17\mathbf{j} + 23\mathbf{k}$ and $\vec{v} = 6\mathbf{i} - 23\mathbf{j} - 18\mathbf{k}$

1.8. $\vec{u} = \mathbf{i}$ and $\vec{v} = \mathbf{j}$. 

What can you say about the result of (1.8.)? Can you deduce similar conclusions for the scalar product of different combinations of the base vectors $\mathbf{i}$, $\mathbf{j}$, $\mathbf{k}$?

### 2 {-}

Find the value(s) of $\lambda$ for which $\vec{u}$ and $\vec{v}$ are perpendicular

2.1. $\vec{u} = \begin{pmatrix}2\\4\\7\end{pmatrix}$ and $\vec{v} = \begin{pmatrix}1\\\lambda\\-2\end{pmatrix}$

2.2. $\vec{u} = \begin{pmatrix}0\\1\\\lambda\end{pmatrix}$ and $\vec{v} = \begin{pmatrix}1\\2\\3\end{pmatrix}$

2.3. $\vec{u} = \begin{pmatrix}9\\-2\\11\end{pmatrix}$ and $\vec{v} = \begin{pmatrix}\lambda\\-\lambda\\3\end{pmatrix}$ 

2.4. $\vec{u} = \begin{pmatrix}\lambda\\6\\1\end{pmatrix}$ and $\vec{v} = \begin{pmatrix}\lambda\\\lambda\\8\end{pmatrix}$ 

2.5. $\vec{u} = \begin{pmatrix}-2\lambda^2\\4\\14\end{pmatrix}$ and $\vec{v} = \begin{pmatrix}3\\2\lambda\\1\end{pmatrix}$ 

2.6. $\vec{u} = \begin{pmatrix}-5\\9\\2\lambda\end{pmatrix}$ and $\vec{v} = \begin{pmatrix}\lambda\\-2\\\lambda\end{pmatrix}$

2.7. $\vec{u} = \begin{pmatrix}-7\\4\\2\lambda\end{pmatrix}$ and $\vec{v} = \begin{pmatrix}2\lambda\\1\\6\lambda\end{pmatrix}$

2.8. $\vec{u} = \begin{pmatrix}-25\\-1\lambda^2\\-2\end{pmatrix}$ and $\vec{v} = \begin{pmatrix}3\lambda\\-11\\7\end{pmatrix}$


## 3 {-}

Find the angle in between $\vec{u}$ and $\vec{v}$ (Hint: Use the Geometric Definition of the Scalar Product)

3.1. $\vec{u} = \begin{pmatrix}-5\\2\\-3\end{pmatrix}$ and $\vec{v} = \begin{pmatrix}2\\-2\\11\end{pmatrix}$

3.2. $\vec{u} = \begin{pmatrix}1\\1\\1\end{pmatrix}$ and $\vec{v} = \begin{pmatrix}1\\-1\\1\end{pmatrix}$

3.3. $\vec{u} = \begin{pmatrix}-8\\1\\-4\end{pmatrix}$ and $\vec{v} = \begin{pmatrix}-1\\-5\\7\end{pmatrix}$

3.4. $\vec{u} = \begin{pmatrix}1.2\\-1.4\\-3.1\end{pmatrix}$ and $\vec{v} = \begin{pmatrix}-5.4\\9.7\\-7.5\end{pmatrix}$

3.5. $\vec{u} = \begin{pmatrix}45\\65\\54\end{pmatrix}$ and $\vec{v} = \begin{pmatrix}-19\\-58\\71\end{pmatrix}$

3.6. $\vec{u} = \begin{pmatrix}1\\0\\0\end{pmatrix}$ and $\vec{v} = \begin{pmatrix}0\\0\\1\end{pmatrix}$

3.7. $\vec{u} = \begin{pmatrix}-1\\-2\\3\end{pmatrix}$ and $\vec{v} = \begin{pmatrix}4\\-5\\6\end{pmatrix}$

3.8. $\vec{u} = \begin{pmatrix}-17\\3\\8\end{pmatrix}$ and $\vec{v} = \begin{pmatrix}12\\-19\\-16\end{pmatrix}$

### 4 {-}

Find $\vec{x}$ such that it is perpendicular to both $\vec{u}$ and $\vec{v}$.

4.1. $\vec{u} = \begin{pmatrix}1\\1\\-3\end{pmatrix}$ and $\vec{v} = \begin{pmatrix}5\\-2\\-1\end{pmatrix}$

4.2. $\vec{u} = \begin{pmatrix}2\\3\\-3\end{pmatrix}$ and $\vec{v} = \begin{pmatrix}1\\-6\\2\end{pmatrix}$

4.3. $\vec{u} = \begin{pmatrix}-8\\1\\-4\end{pmatrix}$ and $\vec{v} = \begin{pmatrix}-1\\-5\\7\end{pmatrix}$




































